# Configuración para despliegue en Netlify

[build]
  publish = "public"
  functions = "functions"

# Configuración de la función serverless para Flask
[functions]
  directory = "functions"

# Redireccionar todo el tráfico a nuestra función de Flask
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

# Configuración de variables de entorno
[build.environment]
  PYTHON_VERSION = "3.12"